name: build-contract

on:
  push:
    branches: ["main"]
  pull_request_target:
    branches: ["main"]
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r rewardsweb/contract/requirements.txt

      - name: "Create Rewards contract env file"
        run: |
          touch rewardsweb/contract/.env
          echo ALGOD_TOKEN_TESTNET="" >> rewardsweb/contract/.env
          echo ALGOD_ADDRESS_TESTNET="https://testnet-api.4160.nodely.dev" >> rewardsweb/contract/.env
          echo ADMIN_TESTNET_MNEMONIC="${{ secrets.ADMIN_TESTNET_MNEMONIC }}" >> rewardsweb/contract/.env
          echo REWARDS_TOKEN_ID_TESTNET="123755640" >> rewardsweb/contract/.env
          echo REWARDS_DAPP_NAME="Rewards" >> rewardsweb/contract/.env
          echo CLAIM_PERIOD_DURATION=3600 >> rewardsweb/contract/.env
          echo ALGOD_SERVER="https://testnet-api.4160.nodely.dev" >> rewardsweb/contract/.env
          echo ALGOD_TOKEN="" >> rewardsweb/contract/.env

      - name: Run tests with coverage
        run: |
          cd rewardsweb
          python -m pytest contract/tests/ -v --cov=contract --cov-branch --cov-report=xml:contract/coverage.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: rewardsweb/contract/coverage.xml
          directory: rewardsweb/contract
          flags: smart-contract
          name: smart-contract-coverage
